#!/bin/bash

cwd=$(pwd)
cd ~/.vim/bundle
for dir in `ls`
do
    cd $dir
    if [[ -n $(ls -a | grep ".git") ]]
    then
        echo Updating $dir...
        git pull
        cd ..
    else
        echo $dir is not on GitHub\; skipping.
    fi
done
